### ISSUE TITLE
:bug: 文件还没下完就开跑了

### ISSUE THREAD

**Issue by Yee36951** [TTB-Network/python-openbmclapi#78]
**问题描述**
Python OpenBMCLAPI 文件还没下完就开跑了

**问题重现**
開始命令：
python main.py

**预期行为**
下完文件才开跑了

**截图**
![photo_2024-05-28_19-56-46](https://github.com/TTB-Network/python-openbmclapi/assets/94163961/2a143a4e-3dc4-4145-a152-2d31093b80fd)

**运行环境**
Python

**版本**
v1.10.8-6e2a352

**其他**
from bytfr

[2024-05-28.log](https://github.com/TTB-Network/python-openbmclapi/files/15469218/2024-05-28.log)
[config.txt](https://github.com/TTB-Network/python-openbmclapi/files/15469258/config.txt)

**Comment by 8MiYile** [comment]
@tianxiu2b2t OneDrive的问题我们一律不解决 具体原因查看这个文档
https://github.com/8Mi-Tech/8Mi-MemeCraftServer/tree/master/lib/BMCLAPI-302#%E5%A6%82%E4%BD%95%E6%90%AD%E5%BB%BA%E4%B8%80%E4%B8%AAbmclapi%E8%8A%82%E7%82%B9---oss%E6%A8%A1%E5%BC%8F

**Comment by SilianZ** [comment]
请注意，在向 python-openbmclapi 提交 issue 的时候，不需要在标题里面附带有 `Python OpenBMCLAPI`、`py版` 等类似字眼，因为你要在 python-openbmclapi 仓库里面发的 issue 只跟 python-openbmclapi 有关，不需要再次在标题里面表明这是 python-openbmclapi 的 issue。
