### ISSUE TITLE
一些关于存储的建议

### ISSUE THREAD

**Issue by Uright-Xuqing233** [TTB-Network/python-openbmclapi#81]
### 在开始之前……

- [X] 我已在 [Issue](https://github.com/TTB-Network/python-openbmclapi/issues) 中搜索过我的建议，确定没有人提出过此建议。

### 建议描述

1. 热上下线存储
在配置文件中添加一个参数
如果短时间某个存储在一定时间内返回错误响应码达到一定数值的时候下线存储，并且一定时间后重试，重启过多就本次运行永久下线
在面板里也能操作存储热上下线

2. 不用检查完所有存储就上线
在一定数值的存储可以使用后上线节点

这些一定的数值可以写在config里

### 如果……

- [ ] 如果可以的话，我可以帮助或自行实现这个功能。

**Comment by xuzhichang** [comment]
对了，希望在面板里也能操作存储热上下线

**Comment by tianxiu2b2t** [comment]
目前已实现该功能？

**Comment by Uright-Xuqing233** [comment]
正确的
