### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by zyxkad** [TTB-Network/python-openbmclapi#93]
### 在开始之前……

- [X] 我已在 [Issue](https://github.com/TTB-Network/python-openbmclapi/issues) 中搜索过我的要上报的漏洞，确定没有人提出过此漏洞。
- [X] 我是用的是最新的 [Release 版本](https://github.com/TTB-Network/python-openbmclapi/releases/latest)而不是最新的 [master 分支](https://github.com/TTB-Network/python-openbmclapi/tree/master)。

### 问题描述

[TTB-Network/python-openbmclapi#installer/installer.sh](https://github.com/TTB-Network/python-openbmclapi/blob/a73aad5d14e1637dd9d646c0c3c30b37f5105eb0/installer/installer.sh) 当中使用了大量出自 [LiterMC/go-openbmclapi#installer/service/installer.sh](https://github.com/LiterMC/go-openbmclapi/blob/dd8238d6dcb3fc1849541c1aeb01ae50ee0d48c0/installer/service/installer.sh) 的代码

<details>
<summary>
根据 <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a> 第五节

</summary>

> 5. Conveying Modified Source Versions.
You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:
> 
>   - a) The work must carry prominent notices stating that you modified it, and giving a relevant date.
>   - b) The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to "keep intact all notices".
>   - c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.
>   - d) If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.
> 
> A compilation of a covered work with other separate and independent works, which are not by their nature extensions of the covered work, and which are not combined with it such as to form a larger program, in or on a volume of a storage or distribution medium, is called an "aggregate" if the compilation and its resulting copyright are not used to limit the access or legal rights of the compilation's users beyond what the individual works permit. Inclusion of a covered work in an aggregate does not cause this License to apply to the other parts of the aggregate.

</details>

您必须明确指出修改日期，并为此脚本（或者整个存储库）声明 AGPL-3.0 或更高版本的协议。

**Comment by SilianZ** [comment]
已在仓库中添加开源法律文件。

另外提醒一下，在 go-openbmclapi 中的 LICENSE 文件中未署名作者和日期：

https://github.com/LiterMC/go-openbmclapi/blob/dd8238d6dcb3fc1849541c1aeb01ae50ee0d48c0/LICENSE#L633

**Comment by zyxkad** [comment]
。。。写在LICENSE下面的东西是 example 不是给你改的。
正确做法应该是把那些东西放到文件里, 如此所示: https://github.com/LiterMC/go-openbmclapi/blob/refactor/installer/service/installer.sh#L2-L16
