### ISSUE TITLE
✨ 支持 AList 存储

### ISSUE THREAD

**Issue by tianxiu2b2t** [TTB-Network/python-openbmclapi#96]
### 在开始之前……

- [X] 我已在 [Issue](https://github.com/TTB-Network/python-openbmclapi/issues) 中搜索过我的建议，确定没有人提出过此建议。

### 建议描述

实现 AList 存储

### 如果……

- [ ] 如果可以的话，我可以帮助或自行实现这个功能。

**Comment by tianxiu2b2t** [comment]
docs: https://alist-doc.nn.ci/docs/api/

**Comment by SilianZ** [comment]
该功能将在 v2.2.0 实现。

**Comment by tianxiu2b2t** [comment]
已在 clusters 分支上实现

**Comment by tianxiu2b2t** [comment]
master 已实现
