### ISSUE TITLE
:star: 支持 OpenMCIM

### ISSUE THREAD

**Issue by WorldHim** [TTB-Network/python-openbmclapi#99]
### 在开始之前……

- [X] 我已在 [Issue](https://github.com/TTB-Network/python-openbmclapi/issues) 中搜索过我的建议，确定没有人提出过此建议。

### 建议描述

[mcmod-info-mirror/mcim](https://github.com/mcmod-info-mirror/mcim)

### 实现方法

[ZeroWolf233/node-openmcim](https://github.com/ZeroWolf233/node-openmcim)

### 如果……

- [ ] 如果可以的话，我可以帮助或自行实现这个功能。

**Comment by unify-z** [comment]
更改配置文件中的主控地址就行了啊

**Comment by WorldHim** [comment]
> 更改配置文件中的主控地址就行了啊

校验会出问题

**Comment by unify-z** [comment]
有日志吗

**Comment by WorldHim** [comment]
> 有日志吗

```
[2024-10-19 06:26:49][ERROR][core.storages.local:writeFile:45]: 无法校验文件 003ab2887711c76fe769a3a57ef1406c3fdc654f 的大小。
```

**Comment by unify-z** [comment]
可能是文件下载失败了，会改源码的话可以改一下输出状态码，或者使用clusters分支看看

**Comment by tianxiu2b2t** [comment]
目前分支已改成 master，试试新的来同步一下？
